Import numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Program Files\\ProjectsCode\\ml-course\\ml-zoomcamp\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>

Creating arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2]

np.int64(3)

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [13]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi dimentional arrays

In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[0]

array([1, 2, 3])

In [20]:
n[:,2]

array([3, 6, 9])

Random generated arrays

In [22]:
np.random.seed(2)

In [23]:
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [25]:
100 * np.random.rand(5, 2)

array([[42.81223276,  9.65309157],
       [12.71599717, 59.6745309 ],
       [22.60120006, 10.69456843],
       [22.03062071, 34.9826285 ],
       [46.77874846, 20.17432263]])

In [26]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[15,  8],
       [17, 22],
       [73, 57],
       [90, 62],
       [83, 96]], dtype=int32)

Element wise operations

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a + 1

array([1, 2, 3, 4, 5])

In [30]:
a * 2

array([0, 2, 4, 6, 8])

In [31]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [34]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

Comparison operations

In [36]:
a >= 2

array([False, False,  True,  True,  True])

In [37]:
a > b

array([False, False,  True,  True,  True])

In [38]:
a[a>b]

array([2, 3, 4])

Summarizing operations

In [39]:
a.min()

np.int64(0)

In [40]:
a.max()

np.int64(4)

In [41]:
a.sum()

np.int64(10)

In [42]:
a.mean()

np.float64(2.0)

In [44]:
a.std()

np.float64(1.4142135623730951)